#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist

class TurtleSquare(Node):
    def __init__(self):
        super().__init__('turtle_square')
        self.publisher = self.create_publisher(Twist, '/turtle1/cmd_vel', 10)
        self.timer = self.create_timer(1.0, self.move_callback)
        self.side_count = 0
        self.state = 'move'
    
    def move_callback(self):
        msg = Twist()
        
        if self.state == 'move':
            msg.linear.x = 1.0
            msg.angular.z = 0.0
        elif self.state == 'turn':
            msg.linear.x = 0.0
            msg.angular.z = 1.57
        
        self.publisher.publish(msg)
        
        if self.state == 'move':
            self.state = 'turn'  
        elif self.state == 'turn':
            self.side_count += 1
            self.state = 'move'  
        
        if self.side_count >= 4:
            self.timer.cancel()
            self.get_logger().info(str(self.side_count))  
            self.get_logger().info("Square Done!!")  

def main(args=None):
    rclpy.init(args=args)
    turtle_square = TurtleSquare()
    rclpy.spin(turtle_square)
    turtle_square.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
